---

- name: Nginx proxy Setup
  when: mailpit_proxy_nginx|bool and mailpit_proxy_domain is defined
  block:

  - name: Install nginx
    ansible.builtin.apt:
      name: "{{ packages }}"
      state: present
      dpkg_options: 'force-confnew,force-confdef'
      autoclean: true
      autoremove: true
      update_cache: true
      cache_valid_time: 3600
    vars:
      packages:
      - nginx

  - name: Add mailpit proxy config
    ansible.builtin.template:
      src: mailpit.nginx.conf
      dest: /etc/nginx/sites-available/mailpit.conf
      owner: root
      group: root
      mode: "0644"

  - name: Check for /etc/nginx/sites-enabled/mailpit.conf
    ansible.builtin.stat:
      path: /etc/nginx/sites-enabled/mailpit.conf
    register: file_status

  - name: Create a symbolic link for mailpit.conf
    ansible.builtin.file:
      src: /etc/nginx/sites-available/mailpit.conf
      dest: /etc/nginx/sites-enabled/mailpit.conf
      owner: root
      group: root
      state: link

  - name: Restart nginx
    ansible.builtin.systemd:
      name: nginx
      state: restarted
    changed_when: file_status.stat.exists is false

...
