---
name: Molecule

# This workflow will act as an includable module
# it will be called by the scheduled workflow and the test workflow
on: workflow_call

jobs:
  molecule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: ${{ github.repository }}

    - name: Run ansible-lint
      uses: ansible/ansible-lint@main

    - name: YAML lint
      working-directory: ${{ github.repository }}
      run: |
        python -m pip install --upgrade pip
        pip install --user yamllint
        yamllint --version
        yamllint .

    - name: Molecule
      uses: gofrolist/molecule-action@v2
      with:
        molecule_command: test --all
        molecule_working_dir: ${{ github.repository }}
      env:
        ANSIBLE_CONFIG: "${{ github.repository }}/ansible.cfg"

...
