---
name: Molecule

# This workflow will act as an includable module
# it will be called by the scheduled workflow and the test workflow
on: workflow_call

jobs:
  molecule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: ${{ github.repository }}

    - name: Prepare local Ansible config
      working-directory: ${{ github.repository }}
      run: |
        mkdir -p collections
        echo "[defaults]" > ansible.cfg
        echo "collections_paths = ./collections:~/.ansible/collections" >> ansible.cfg

    - name: Install dependencies
      working-directory: ${{ github.repository }}
      run: |
        python -m pip install --upgrade pip
        pip install --user ansible ansible-lint yamllint
        ansible-galaxy collection install --force -r requirements.yml --collections-path ./collections

    - name: Lint playbook
      working-directory: ${{ github.repository }}
      env:
        ANSIBLE_CONFIG: "${{ github.repository }}/ansible.cfg"
      run: |
        yamllint --version
        yamllint .
        ansible-lint .

    - name: Molecule
      uses: gofrolist/molecule-action@v2
      with:
        molecule_command: test --all
        molecule_working_dir: ${{ github.repository }}
      env:
        ANSIBLE_CONFIG: "${{ github.repository }}/ansible.cfg"

...
