---
name: Molecule

# This workflow will act as an includable module
# it will be called by the scheduled workflow and the test workflow
on: workflow_call

jobs:
  molecule:
    runs-on: ubuntu-latest
    env:
      PYTHONUSERBASE: /home/runner/.local
      ANSIBLE_LOCAL_TEMP: /home/runner/.ansible/tmp
      ANSIBLE_COLLECTIONS_PATH: /home/runner/.ansible/collections

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: ${{ github.repository }}

    - name: Setup directories
      run: |
        mkdir -p $PYTHONUSERBASE
        mkdir -p $ANSIBLE_LOCAL_TEMP
        mkdir -p $ANSIBLE_COLLECTIONS_PATH

    - name: Install dependencies
      working-directory: ${{ github.repository }}
      run: |
        python -m pip install --upgrade pip
        export PATH="$PYTHONUSERBASE/bin:$PATH"
        pip install --user ansible ansible-lint yamllint
        ansible-galaxy collection install -r requirements.yml --collections-path $ANSIBLE_COLLECTIONS_PATH

    - name: Lint playbook
      working-directory: ${{ github.repository }}
      run: |
        export PATH="$PYTHONUSERBASE/bin:$PATH"
        yamllint --version
        yamllint .
        ansible-lint .

    - name: Molecule
      uses: gofrolist/molecule-action@v2
      with:
        molecule_command: test --all
        molecule_args: -d docker
        molecule_working_dir: ${{ github.repository }}
